xarm7:
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  # kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_search_resolution: 0.005 #0.00001
  kinematics_solver_timeout: 0.5 #0.02 #0.1 #0.02
  kinematics_solver_attempts: 100.0 #50.0
  mode: gd_c #bio2_memetic #jac_2 #gd_c_2
  center_joints_weight: 1.0 #1.0
  minimal_displacement_weight: 50.0 #80.0 #100.0 #100.0
  avoid_joint_limits_weight: 1.0 #0.5

  # pick_ik parameters
  # mode: local
  # stop_optimization_on_valid_solution: false #true
  # position_scale: 1.0
  # rotation_scale: 1.0 #0.5
  # position_threshold: 1.0 #0.1 #0.01
  # orientation_threshold: 1.0 #0.1 #0.01
  # cost_threshold: 1.0 #0.1 #0.001
  # minimal_displacement_weight: 1.0 #0.1 #0.001 #0.0
  # gd_step_size: 0.001 #0.0001
